package main.nodes.expression;

public enum ExpressionType {
    PLUS, MINUS, MUL, DIV, EQUAL, NOT_EQUAL, GREATER, LESS, GREATER_EQUAL, LESS_EQUAL, QT, U_MINUS, NEG, OR, AND, ASGN,
    BREAK, CONTINUE, RETURN, ARRAY, ARRAY_AUTO_FILL, INDEX, RANGE, RANGE_IN, RANGE_LEFT, RANGE_RIGHT, RANGE_IN_RIGHT,
    ID, SELF, CALL, METHOD, FIELD_ACCESS, IF, LOOP, LOOP_WHILE, LOOP_FOR, BLOCK, INT_LIT, FLOAT_LIT, CHAR_LIT,
    STRING_LIT, BOOL_LIT, STRUCT, STRUCT_FIELD, STATIC_METHOD, INDEX_ASGN, FIELD_ASGN
}
