/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 119
#define YY_END_OF_BUFFER 120
static yyconst short int yy_accept[308] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      120,  119,  118,   93,   45,  109,   58,  101,  102,   79,
       77,  106,   78,  108,   80,  111,  111,  107,  105,   87,
       90,   88,  110,  110,   99,  100,   91,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  103,  119,  104,   46,   57,   56,   70,   71,
       72,   75,   76,   60,   68,  119,   89,   95,    0,    0,
       83,   81,   82,   98,   96,   69,   74,   84,    0,  111,
      117,  117,  111,  117,  117,  117,  117,  117,   85,   92,
       86,  110,  110,    1,  110,  110,  110,  110,  110,  110,

      110,  110,  110,  110,  110,  110,    9,  110,  110,   12,
      110,   14,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,   94,   46,   47,
       53,   54,   51,   48,   49,   52,   50,    0,   70,   73,
       60,   66,   67,   64,   61,   62,   65,   63,    0,    0,
        0,   97,  113,  117,    0,  112,  117,  111,  117,  111,
      117,  117,  116,  117,  117,  117,  114,  117,  115,  117,
      110,  110,  110,  110,  110,  110,  110,  110,   37,  110,
      110,  110,   15,  110,   10,   11,  110,   16,  110,  110,
       19,  110,   21,   22,   23,  110,  110,  110,  110,  110,

      110,  110,  110,  110,   32,  110,  110,   47,    0,    0,
        0,    0,  113,    0,  113,    0,  112,    0,  112,  112,
      117,  117,  113,  111,  117,  117,  110,  110,  110,   40,
      110,   39,  110,  110,  110,    6,    7,  110,  110,   13,
       17,  110,   20,  110,   25,  110,  110,  110,  110,   44,
       30,  110,  110,  110,   55,    0,    0,   41,  113,    0,
      112,  112,    0,  117,  117,  117,  117,  110,   35,   36,
        2,    3,  110,    5,  110,   43,   18,  110,  110,  110,
       28,   29,  110,   33,   34,   59,    0,  113,    0,  112,
      116,  114,  115,   38,  110,    8,   24,   26,   27,   31,

        0,  112,  110,    0,    4,   42,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   22,   24,   24,   25,   26,   27,
       28,   29,    1,    1,   30,   30,   30,   30,   31,   30,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   33,   32,   32,   32,   32,   32,   32,   32,
       34,   35,   36,   37,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   32,   48,   49,   50,   51,
       52,   53,   32,   54,   55,   56,   57,   58,   59,   60,
       61,   32,   62,   63,   64,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    3,    1,    1,
        4,    5,    1,    5,    1,    4,    6,    6,    6,    6,
        6,    6,    6,    6,    1,    1,    1,    1,    1,    7,
        8,    9,    9,    1,   10,    1,    1,   11,    7,    7,
        7,    7,    8,   12,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    1,    1,    1
    } ;

static yyconst short int yy_base[322] =
    {   0,
        0,    0,   59,   60,   56,   57,  560,  559,   61,   62,
      561,  564,  564,  532,  564,   64,  564,  564,  564,  531,
      530,  564,   46,  542,   65,  105,   38,  564,  564,  528,
      527,  526,    0,  497,  564,  564,  564,   24,   28,   53,
      491,   40,   64,   89,   34,   49,  494,  507,   61,   31,
       57,  503,  564,  485,  564,    0,  564,  164,    0,  531,
      564,  564,  564,    0,  564,  163,  564,  564,  489,  502,
      564,  564,  564,  564,  516,  564,  564,  564,  165,  150,
        0,  213,  237,   93,  520,  522,  156,  268,  564,  564,
      564,    0,  487,  479,  500,  486,  494,  497,  484,  495,

      482,  477,  474,  474,  508,  479,    0,  473,  507,    0,
      472,    0,  468,  471,  466,  149,  465,  480,   86,  470,
      154,  465,   45,  464,  461,  472,  149,  564,    0,  198,
      564,  564,  564,  564,  564,  564,  564,  221,    0,  564,
        0,  564,  564,  564,  564,  564,  564,  564,  296,  458,
      464,  564,  178,    0,  303,  325,  120,    0,    0,    0,
      489,  491,  229,  188,  489,  490,  461,    0,  460,    0,
      459,  454,  457,  454,  461,  445,  148,  442,    0,  454,
      444,  450,    0,  437,    0,    0,  442,    0,  434,  445,
        0,  442,    0,    0,    0,  423,  435,  422,  415,  428,

      422,  422,  415,  412,    0,  386,  385,  209,    0,    0,
      246,  382,  234,  257,  262,  399,  226,  312,    0,    0,
      345,  347,    0,    0,  346,  345,  313,  321,  305,    0,
      312,    0,  303,  311,  314,    0,    0,  302,  312,    0,
        0,  307,    0,  298,    0,  304,  299,  285,  282,    0,
        0,  293,  285,  261,  564,  289,  299,  564,    0,  275,
      235,    0,  271,  262,  263,  255,  247,  218,    0,    0,
        0,    0,  211,    0,  202,    0,    0,  194,  188,  172,
        0,    0,  170,    0,    0,  564,  154,  564,  174,    0,
        0,    0,    0,    0,  111,    0,    0,    0,    0,    0,

       92,  564,   78,   69,    0,  564,  564,  369,  381,  393,
      405,  412,  424,  436,  448,  455,  462,  469,  476,  484,
      490
    } ;

static yyconst short int yy_def[322] =
    {   0,
      307,    1,  308,  308,  309,  309,  310,  310,  311,  311,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,   26,  307,  307,  307,
      307,  307,  312,  312,  307,  307,  307,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  307,  307,  307,  313,  307,  307,  314,  307,
      307,  307,  307,  315,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,   26,
      316,  316,  316,  316,  316,  316,  316,  316,  307,  307,
      307,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  307,  313,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  314,  307,
      315,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  317,  316,  307,  316,   82,   83,   82,   83,
      316,  316,  316,  316,  316,  316,   87,   87,   88,   88,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  307,  318,  319,
      307,  307,  317,  320,  213,  307,  321,  307,  156,  156,
      316,  316,  316,  316,  316,  316,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  307,  307,  307,  307,  213,  307,
      321,  261,  307,  316,  316,  316,  316,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  307,  307,  307,  307,  316,
      316,  316,  316,  312,  312,  312,  312,  312,  312,  312,

      307,  307,  312,  307,  312,  307,    0,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307
    } ;

static yyconst short int yy_nxt[629] =
    {   0,
       12,   13,   13,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   27,   27,
       27,   27,   27,   27,   28,   29,   30,   31,   32,   33,
       33,   33,   34,   35,   12,   36,   37,   33,   38,   39,
       40,   41,   42,   43,   33,   33,   44,   33,   45,   46,
       33,   33,   47,   48,   49,   50,   51,   33,   52,   33,
       33,   53,   54,   55,   57,   57,   60,   60,   65,   65,
       68,   61,   61,   73,   74,   76,  113,   81,   94,   96,
       77,   97,   95,  201,  123,  114,  105,  115,  102,   81,
      103,  124,   78,   58,   58,   66,   66,   81,   98,  104,

      116,  202,  106,  120,   99,  117,  100,  125,  109,  163,
      163,  126,  306,   69,  107,  108,  121,  122,   70,   79,
      305,   80,   80,   80,   80,   80,   80,   80,   80,  195,
      164,  307,  110,  307,   81,   82,   81,   81,  111,  112,
      304,  196,   83,   81,   84,   81,   81,   82,   85,   81,
       81,   86,   81,   81,   81,   81,   87,   81,   81,   81,
       81,   81,   81,   81,   88,   81,  130,  303,  142,  131,
      143,  132,  167,  167,  167,  167,  167,  167,  167,  144,
      133,  153,  153,  153,  153,  153,  153,  153,  153,   81,
      191,  206,  198,  168,  302,  207,  301,  145,  134,  208,

      208,   81,  233,  234,  163,  163,  192,  199,  214,   81,
      208,  208,  300,  146,  135,  215,  147,  136,  148,  137,
      214,  216,  149,  138,  155,  164,  155,  299,  298,  156,
      156,  156,  156,  156,  156,  156,  156,  209,  209,  209,
      209,  209,  209,  209,  297,  163,  163,  257,  257,  257,
      157,   79,  296,  158,  158,  158,  158,  158,  158,  158,
      158,  295,  294,  262,  307,  293,  164,  159,  155,  263,
      155,  259,  262,  292,  160,  222,  307,  216,  263,  159,
      161,  291,  290,  162,  169,  169,  169,  169,  169,  169,
      169,  169,  214,  289,  218,  288,  286,  169,  169,  215,

      257,  257,  257,  285,  214,  170,  169,  169,  169,  169,
      169,  169,  210,  210,  210,  210,  210,  210,  210,  217,
      217,  217,  217,  217,  217,  217,  217,  284,  217,  217,
      217,  217,  217,  217,  217,  217,  283,  282,  281,  280,
      218,  219,  219,  219,  219,  219,  219,  219,  219,  218,
      279,  278,  277,  287,  276,  275,  274,  273,  272,  271,
      270,  269,  220,  268,  267,  266,  265,  264,  221,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   62,   62,   62,   62,   62,   62,   62,

       62,   62,   62,   62,   62,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   92,   92,   92,
       92,  260,   92,   92,  129,  258,  129,  129,  129,  129,
      129,  129,  129,  254,  129,  129,  139,  139,  139,  253,
      139,  139,  139,  139,  139,  139,  139,  139,  141,  141,
      252,  141,  141,  141,  141,  141,  141,  251,  141,  141,
      154,  154,  154,  154,  250,  154,  154,  213,  249,  213,
      248,  247,  213,  213,  255,  255,  255,  246,  245,  244,
      255,  256,  256,  256,  243,  242,  241,  256,  217,  217,
      240,  239,  238,  237,  217,  261,  236,  235,  232,  231,

      261,  261,  230,  229,  228,  227,  226,  225,  224,  223,
      166,  165,  212,  211,  205,  204,  203,  200,  197,  194,
      193,  190,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  166,  165,  152,  151,  150,  140,  128,  127,  119,
      118,  101,   93,   91,   90,   89,   75,   72,   71,   67,
      307,   63,   63,   11,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307
    } ;

static yyconst short int yy_chk[629] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    5,    6,    9,   10,
       16,    5,    6,   23,   23,   25,   45,   27,   38,   39,
       25,   39,   38,  123,   50,   45,   43,   46,   42,   27,
       42,   50,   25,    3,    4,    9,   10,   27,   40,   42,

       46,  123,   43,   49,   40,   46,   40,   51,   44,   84,
       84,   51,  304,   16,   43,   43,   49,   49,   16,   26,
      303,   26,   26,   26,   26,   26,   26,   26,   26,  119,
       84,  157,   44,  157,   26,   26,   26,   26,   44,   44,
      301,  119,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   58,  295,   66,   58,
       66,   58,   87,   87,   87,   87,   87,   87,   87,   66,
       58,   79,   79,   79,   79,   79,   79,   79,   79,   80,
      116,  127,  121,   87,  289,  127,  287,   66,   58,  130,

      130,   80,  177,  177,  164,  164,  116,  121,  153,   80,
      208,  208,  283,   66,   58,  153,   66,   58,   66,   58,
      153,  153,   66,   58,   82,  164,   82,  280,  279,   82,
       82,   82,   82,   82,   82,   82,   82,  138,  138,  138,
      138,  138,  138,  138,  278,  163,  163,  211,  211,  211,
       82,   83,  275,   83,   83,   83,   83,   83,   83,   83,
       83,  273,  268,  217,  213,  267,  163,   83,  214,  217,
      214,  213,  261,  266,   83,  163,  213,  213,  261,   83,
       83,  265,  264,   83,   88,   88,   88,   88,   88,   88,
       88,   88,  215,  263,  214,  260,  256,   88,   88,  215,

      257,  257,  257,  254,  215,   88,   88,   88,   88,   88,
       88,   88,  149,  149,  149,  149,  149,  149,  149,  155,
      155,  155,  155,  155,  155,  155,  155,  253,  218,  218,
      218,  218,  218,  218,  218,  218,  252,  249,  248,  247,
      155,  156,  156,  156,  156,  156,  156,  156,  156,  218,
      246,  244,  242,  257,  239,  238,  235,  234,  233,  231,
      229,  228,  156,  227,  226,  225,  222,  221,  156,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  310,  310,  310,  310,  310,  310,  310,

      310,  310,  310,  310,  310,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  312,  312,  312,
      312,  216,  312,  312,  313,  212,  313,  313,  313,  313,
      313,  313,  313,  207,  313,  313,  314,  314,  314,  206,
      314,  314,  314,  314,  314,  314,  314,  314,  315,  315,
      204,  315,  315,  315,  315,  315,  315,  203,  315,  315,
      316,  316,  316,  316,  202,  316,  316,  317,  201,  317,
      200,  199,  317,  317,  318,  318,  318,  198,  197,  196,
      318,  319,  319,  319,  192,  190,  189,  319,  320,  320,
      187,  184,  182,  181,  320,  321,  180,  178,  176,  175,

      321,  321,  174,  173,  172,  171,  169,  167,  166,  165,
      162,  161,  151,  150,  126,  125,  124,  122,  120,  118,
      117,  115,  114,  113,  111,  109,  108,  106,  105,  104,
      103,  102,  101,  100,   99,   98,   97,   96,   95,   94,
       93,   86,   85,   75,   70,   69,   60,   54,   52,   48,
       47,   41,   34,   32,   31,   30,   24,   21,   20,   14,
       11,    8,    7,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "input.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#define CONST_STRING 1

#define MULTILINE_COMMENT 2

#define ONELINE_COMMENT 3

#define CHAR_ 4

#line 12 "input.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "nodes.h"
#include "stdbool.h"
#include "grammar_with_code.tab.h"
#line 625 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 20 "input.l"



int remove_char(char *s, int pos);
void remove_underline();
void remove_f64();
void remove_i32();
int int_buffer;
char buf_char[2];
char buffer[1000];


#line 785 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 308 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 564 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 32 "input.l"
{ printf("(%s) - Found KW_AS\n", yytext);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 33 "input.l"
{ printf("(%s) - Found KW_BREAK\n", yytext); return BREAK;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 34 "input.l"
{ printf("(%s) - Found KW_CONST\n", yytext); return CONST;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 35 "input.l"
{ printf("(%s) - Found KW_CONTINUE\n", yytext); return CONTINUE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 36 "input.l"
{ printf("(%s) - Found KW_CRATE\n", yytext); return CRATE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 37 "input.l"
{ printf("(%s) - Found KW_ELSE\n", yytext); return ELSE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 38 "input.l"
{ printf("(%s) - Found KW_ENUM\n", yytext); return ENUM;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 39 "input.l"
{ printf("(%s) - Found KW_EXTERN\n", yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 40 "input.l"
{ printf("(%s) - Found KW_FN\n", yytext); return FN;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 41 "input.l"
{ printf("(%s) - Found KW_FOR\n", yytext); return FOR;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 42 "input.l"
{ printf("(%s) - Found KW_INT\n", yytext); return INT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 43 "input.l"
{ printf("(%s) - Found KW_IF\n", yytext); return IF;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 44 "input.l"
{ printf("(%s) - Found KW_IMPL\n", yytext); return IMPL;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 45 "input.l"
{ printf("(%s) - Found KW_IN\n", yytext); return IN;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 46 "input.l"
{ printf("(%s) - Found KW_FLOAT\n", yytext); return FLOAT;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 47 "input.l"
{ printf("(%s) - Found KW_LET\n", yytext); return LET;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 48 "input.l"
{ printf("(%s) - Found KW_LOOP\n", yytext); return LOOP;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 49 "input.l"
{ printf("(%s) - Found KW_MATCH\n", yytext);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 50 "input.l"
{ printf("(%s) - Found KW_MOD\n", yytext);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 51 "input.l"
{ printf("(%s) - Found KW_MOVE\n", yytext);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 52 "input.l"
{ printf("(%s) - Found KW_MUT\n", yytext); return MUT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 53 "input.l"
{ printf("(%s) - Found KW_PUB\n", yytext); return PUB;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 54 "input.l"
{ printf("(%s) - Found KW_REF\n", yytext);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 55 "input.l"
{ printf("(%s) - Found KW_RETURN\n", yytext); return RETURN;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 56 "input.l"
{ printf("(%s) - Found KW_SELFVALUE\n", yytext); return SELF;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 57 "input.l"
{ printf("(%s) - Found KW_STATIC\n", yytext);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 58 "input.l"
{ printf("(%s) - Found KW_STRUCT\n", yytext); return STRUCT;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "input.l"
{ printf("(%s) - Found KW_SUPER\n", yytext); return SUPER;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "input.l"
{ printf("(%s) - Found KW_TRAIT\n", yytext); return TRAIT;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 61 "input.l"
{ printf("(%s) - Found KW_TYPE\n", yytext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 62 "input.l"
{ printf("(%s) - Found KW_UNSAFE\n", yytext);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 63 "input.l"
{ printf("(%s) - Found KW_USE\n", yytext);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 64 "input.l"
{ printf("(%s) - Found KW_WHERE\n", yytext);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 65 "input.l"
{ printf("(%s) - Found KW_WHILE\n", yytext); return WHILE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 66 "input.l"
{ printf("(%s) - Found KW_ASYNC\n", yytext);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 67 "input.l"
{ printf("(%s) - Found KW_AWAITE\n", yytext);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 68 "input.l"
{ printf("(%s) - Found KW_DYN\n", yytext);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 69 "input.l"
{ printf("(%s) - Found KW_STRING\n", yytext); return STRING;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 70 "input.l"
{ printf("(%s) - Found KW_CHAR\n", yytext); return CHAR;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 71 "input.l"
{ printf("(%s) - Found KW_BOOLEAN\n", yytext); return BOOL;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 72 "input.l"
{ printf("(%s) - Found KW_SELF_PARAM\n", yytext); return SELF_PARAM;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 73 "input.l"
{ printf("(%s) - Found KW_MUT_SELF_PARAM\n", yytext); return MUT_SELF_PARAM;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 75 "input.l"
{ printf("(%s) - Found BOOLEAN_FALSE\n", yytext); return FALSE;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 76 "input.l"
{ printf("(%s) - Found BOOLEAN_TRUE\n", yytext); return TRUE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 78 "input.l"
{buffer[0]=0; BEGIN(CONST_STRING);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 79 "input.l"
{strcat(buffer,yytext);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 80 "input.l"
{strcat(buffer, "");}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 81 "input.l"
{strcat(buffer, "\\");}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 82 "input.l"
{strcat(buffer, "\n");}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 83 "input.l"
{strcat(buffer, "\t");}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 84 "input.l"
{strcat(buffer, "\0");}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 85 "input.l"
{strcat(buffer, "\r");}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 86 "input.l"
{strcat(buffer, "\"");}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 87 "input.l"
{strcat(buffer, "\'");}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 88 "input.l"
{ buf_char[0] = strtol(yytext+2, NULL, 16); buf_char[1] = 0; strcat(buffer, buf_char);}
	YY_BREAK
case YY_STATE_EOF(CONST_STRING):
#line 89 "input.l"
{printf("(%s) - Error ERROR_STRING\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 90 "input.l"
{printf("(%s) - Error NOT_ESCAPED_SLASH\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 91 "input.l"
{
printf("(%s) - Found CONST_STRING\n", buffer); BEGIN(INITIAL);
yylval.string_const=(char *)malloc(strlen(buffer)+1);
strcpy(yylval.string_const, buffer);
return STRING_LITERAL;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 98 "input.l"
{buffer[0]=0; BEGIN(CHAR_);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 99 "input.l"
{ yytext[strlen(yytext)-1] = '\0'; buf_char[0] = strtol(yytext+2, NULL, 16); printf( "(%c) - Found CHAR\n", buf_char[0] ); BEGIN(INITIAL);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 100 "input.l"
{strcat(buffer,yytext);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 101 "input.l"
{strcat(buffer, "\\");}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 102 "input.l"
{strcat(buffer, "\n");}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 103 "input.l"
{strcat(buffer, "\t");}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 104 "input.l"
{strcat(buffer, "\0");}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 105 "input.l"
{strcat(buffer, "\r");}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 106 "input.l"
{strcat(buffer, "\"");}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 107 "input.l"
{strcat(buffer, "\'");}
	YY_BREAK
case YY_STATE_EOF(CHAR_):
#line 108 "input.l"
{printf("(%s) - Error CHAR\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 109 "input.l"
{
if(strlen(buffer)==1){
printf("(%s) - Found CHAR\n", buffer); BEGIN(INITIAL);
yylval.char_const=buffer[0];
return CHAR_LITERAL;
}else{
printf("(%s) - Error CHAR\n", buffer); BEGIN(INITIAL);
}
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 119 "input.l"
{buffer[0]=0; BEGIN(MULTILINE_COMMENT);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 120 "input.l"
{strcat(buffer,yytext);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 121 "input.l"
{strcat(buffer, "*");}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 122 "input.l"
{strcat(buffer, "/");}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 123 "input.l"
{ printf("(%s) - Error COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 124 "input.l"
{printf("(%s) - Found MULTILINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 126 "input.l"
{buffer[0]=0; BEGIN(ONELINE_COMMENT);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 127 "input.l"
{strcat(buffer, yytext);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 128 "input.l"
{printf("(%s) - Found ONELINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(ONELINE_COMMENT):
#line 129 "input.l"
{printf("(%s) - Found ONELINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 132 "input.l"
{ printf("(%s) - Found PLUS_OPERATOR\n", yytext); return '+';}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 133 "input.l"
{ printf("(%s) - Found MINUS_OPERATOR\n", yytext); return '-';}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 134 "input.l"
{ printf("(%s) - Found MUL_OPERATOR\n", yytext); return '*';}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 135 "input.l"
{ printf("(%s) - Found DIV_OPERATOR\n", yytext); return '/';}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 136 "input.l"
{ printf("(%s) - Found PLUS_ASSIGNMENT_OPERATOR\n", yytext);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 137 "input.l"
{ printf("(%s) - Found MINUS_ASSIGNMENT_OPERATOR\n", yytext);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 138 "input.l"
{ printf("(%s) - Found MUL_ASSIGNMENT_OPERATOR\n", yytext);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 139 "input.l"
{ printf("(%s) - Found DIV_ASSIGNMENT_OPERATOR\n", yytext);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 140 "input.l"
{ printf("(%s) - Found LESS_OR_EQUAL_OPERATOR\n", yytext); return LESS_EQUAL;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 141 "input.l"
{ printf("(%s) - Found MORE_OR_EQUAL_OPERATOR\n", yytext); return GREATER_EQUAL;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 142 "input.l"
{ printf("(%s) - Found LESS_OPERATOR\n", yytext); return '<';}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 143 "input.l"
{ printf("(%s) - Found MORE_OPERATOR\n", yytext); return '>';}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 144 "input.l"
{ printf("(%s) - Found NOT_EQUAL_OPERATOR\n", yytext); return NOT_EQUAL;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 145 "input.l"
{ printf("(%s) - Found ASSIGNMENT_OPERATOR\n", yytext); return '=';}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 146 "input.l"
{ printf("(%s) - Found CIRCUMFLEX\n", yytext);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 149 "input.l"
{ printf("(%s) - Found EQUAL_OPERATOR\n", yytext); return EQUAL;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 150 "input.l"
{ printf("(%s) - Found NOT_OPERATOR\n", yytext); return '!';}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 151 "input.l"
{ printf("(%s) - Found OR_OPERATOR\n", yytext); return OR;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 152 "input.l"
{ printf("(%s) - Found AND_OPERATOR\n", yytext); return AND;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 154 "input.l"
{ printf("(%s) - Found RANGE_OPERATOR\n", yytext); return RANGE;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 155 "input.l"
{ printf("(%s) - Found RANGE_EQUAL_OPERATOR\n", yytext); return RANGE_IN;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 156 "input.l"
{ printf("(%s) - Found ARROW_OPERATOR\n", yytext); return RIGHT_ARROW;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 158 "input.l"
{ printf("(%s) - Found SQUARE_BRACKET\n", yytext); return '[';}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 159 "input.l"
{ printf("(%s) - Found SQUARE_BRACKET\n", yytext); return ']';}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 160 "input.l"
{ printf("(%s) - Found ROUND_BRACKET\n", yytext); return '(';}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 161 "input.l"
{ printf("(%s) - Found ROUND_BRACKET\n", yytext); return ')';}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 162 "input.l"
{ printf("(%s) - Found BRACE\n", yytext); return '{';}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 163 "input.l"
{ printf("(%s) - Found BRACE\n", yytext); return '}';}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 164 "input.l"
{ printf("(%s) - Found SEMICOLON\n", yytext); return ';';}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 165 "input.l"
{ printf("(%s) - Found COMMA\n", yytext); return ',';}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 166 "input.l"
{ printf("(%s) - Found COLON\n", yytext); return ':';}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 167 "input.l"
{ printf("(%s) - Found DOT\n", yytext); return '.';}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 168 "input.l"
{ printf("(%s) - Found AMPERSAND\n", yytext); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 170 "input.l"
{
printf("(%s) - Found IDENTIFIER\n", yytext);
yylval.string_const=(char *)malloc(strlen(yytext)+1);
strcpy(yylval.string_const, yytext);
return ID;
}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 177 "input.l"
{
strcpy(buffer, yytext);
remove_underline(buffer);
remove_i32(buffer);
printf("(%d) - Found DECIMAL_INTEGER\n", atoi(buffer));
yylval.int_const=atoi(buffer);
return INT_LITERAL;
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 186 "input.l"
{
strcpy(buffer, yytext);
remove_underline(buffer);
remove_f64(buffer);
printf("(%f) - Found FLOAT_CONST\n", atof(buffer));
yylval.float_const=atof(buffer);
return FLOAT_LITERAL;
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 195 "input.l"
{
strcpy(buffer, yytext);
remove_underline(buffer);
remove_f64(buffer);
printf("(%f) - Found FLOAT_CONST\n", atof(buffer));
yylval.float_const=atof(buffer);
return FLOAT_LITERAL;
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 204 "input.l"
{
strcpy(buffer, yytext);
remove_underline(buffer);
remove_i32(buffer);
printf("(%d) - Found OCTAL_INTEGER\n", strtol(buffer+2, NULL, 8));
yylval.float_const=strtol(buffer+2, NULL, 8);
return INT_LITERAL;
}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 213 "input.l"
{
strcpy(buffer, yytext);
remove_underline(buffer);
remove_i32(buffer);
printf("(%d) - Found HEXADECIMAL_INTEGER\n", strtol(buffer+2, NULL, 16));
yylval.int_const=strtol(buffer+2, NULL, 16);
return INT_LITERAL;
}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 222 "input.l"
{
strcpy(buffer, yytext);
remove_underline(buffer);
remove_i32(buffer);
printf("(%d) - Found BINARY_INTEGER\n", strtol(buffer+2, NULL, 2));
yylval.int_const=strtol(buffer+2, NULL, 2);
return INT_LITERAL;
}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 231 "input.l"
{ printf("(%s) - Error IDENTIFIER\n", yytext); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 233 "input.l"
{}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 235 "input.l"
ECHO;
	YY_BREAK
#line 1539 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 308 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 308 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 307);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 235 "input.l"


int remove_char(char *s, int pos)
{
  int length = strlen(s);

  if (pos >= length) return 0;

  for (int i = pos; i < length; i++)
    s[i] = s[i + 1];

  return 1;
}

void remove_underline(char* buffer)
{
    char* ptr = strchr(buffer, '_');
    while (ptr != NULL){
        ptr = strchr(buffer, '_');
        int pos = ptr - buffer;
        remove_char(buffer, pos);
    }
}

void remove_f64(char* buffer)
{
    char* ptr = strstr(buffer, "f64");
    if (ptr != NULL){
        int pos = ptr - buffer;
        buffer[pos] = '\0';
    }
}

void remove_i32(char* buffer)
{
    char* ptr = strstr(buffer, "i32");
        if (ptr != NULL){
            int pos = ptr - buffer;
            buffer[pos] = '\0';
        }
}