/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 114
#define YY_END_OF_BUFFER 115
static yyconst short int yy_accept[295] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      115,  114,  113,  112,   87,   44,  103,   57,   95,   96,
       78,   76,  100,   77,  102,   79,  105,  105,  101,   99,
       82,   85,   83,  104,  104,   93,   94,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,   97,  114,   98,   45,   56,   55,   69,   70,
       71,   74,   75,   59,   67,  114,   84,   89,   92,   90,
       68,   73,    0,  105,  111,  111,  105,  111,  111,  111,
      111,  111,   80,   86,   81,  104,  104,  104,    1,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,

      104,    9,  104,  104,   12,  104,   14,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,   88,   45,   46,   52,   53,   50,   47,   48,
       51,   49,    0,   69,   72,   59,   65,   66,   63,   60,
       61,   64,   62,    0,   91,  107,  111,    0,  106,  111,
      105,  111,  105,  111,  111,  110,  111,  111,  111,  108,
      111,  109,  111,  104,  104,  104,  104,  104,  104,  104,
      104,  104,   37,  104,  104,  104,   11,  104,   10,   38,
      104,   15,  104,  104,   18,  104,   20,   21,   22,  104,
      104,  104,  104,  104,  104,  104,  104,  104,   32,  104,

      104,   46,    0,    0,  107,    0,  107,    0,  106,    0,
      106,  106,  111,  111,  107,  105,  111,  111,   25,  104,
      104,  104,   41,  104,   40,  104,  104,  104,    6,    7,
      104,  104,   13,   16,  104,   19,  104,   24,  104,  104,
      104,  104,   43,   30,  104,  104,  104,   54,    0,  107,
        0,  106,  106,    0,  111,  111,  111,  111,  104,   35,
       36,    2,    3,  104,    5,  104,   42,   17,  104,  104,
      104,   28,   29,  104,   33,   34,   58,  107,    0,  106,
      110,  108,  109,   39,  104,    8,   23,   26,   27,   31,
      106,  104,    4,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   22,   24,   24,   25,   26,   27,
       28,   29,    1,    1,   30,   30,   30,   30,   31,   30,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   33,   32,   32,   32,   32,   32,   32,   32,
       34,   35,   36,    1,   37,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   32,   47,   48,   49,   50,
       51,   52,   32,   53,   54,   55,   56,   57,   58,   59,
       60,   32,   61,   62,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    3,    1,    1,
        4,    5,    1,    5,    1,    4,    6,    6,    6,    6,
        6,    6,    6,    6,    1,    1,    1,    1,    1,    7,
        8,    9,    9,    1,   10,    1,   11,    7,    7,    7,
        7,    8,   12,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        1,    1,    1
    } ;

static yyconst short int yy_base[309] =
    {   0,
        0,    0,   58,   59,   55,   56,  543,  542,   60,   61,
      544,  547,  547,  547,  515,  547,  535,  547,  547,  547,
      547,  547,  547,  512,  525,   59,   82,   39,  547,  547,
      511,  510,  509,    0,   31,  547,  547,   22,   26,   36,
      476,   59,  120,  124,   32,  108,  479,  492,  105,   31,
       38,  488,  547,  470,  547,    0,  547,  145,    0,  515,
      547,  547,  547,    0,  547,  146,  547,  547,  547,  502,
      547,  547,  165,  106,    0,  194,  217,  132,  506,  508,
      205,  247,  547,  547,  547,    0,  479,  473,  465,  486,
      472,  480,  483,  470,  481,  468,  463,  460,  460,  493,

      465,    0,  459,  492,    0,  458,    0,  454,  457,  452,
      115,  451,  466,  123,  456,  137,  451,  138,  450,  447,
      458,  151,  547,    0,  217,  547,  547,  547,  547,  547,
      547,  547,  274,    0,  547,    0,  547,  547,  547,  547,
      547,  547,  547,  281,  547,  213,    0,  288,  309,   96,
        0,    0,    0,  476,  478,  212,  235,  476,  477,  449,
        0,  448,    0,  450,  446,  441,  444,  441,  450,  434,
       62,  431,    0,  441,  433,  439,    0,  426,    0,    0,
      429,    0,  424,  435,    0,  432,    0,    0,    0,  414,
      426,  413,  407,  420,  415,  413,  412,  414,    0,  395,

      393,  243,    0,    0,  305,  165,  220,  411,  166,  297,
        0,    0,  400,  397,    0,    0,  389,  385,    0,  301,
      310,  294,    0,  298,    0,  289,  297,  299,    0,    0,
      287,  297,    0,    0,  293,    0,  284,    0,  289,  284,
      270,  267,    0,    0,  270,  241,  240,  547,  273,    0,
      259,  236,    0,  253,  254,  255,  242,  224,  189,    0,
        0,    0,    0,  160,    0,  157,    0,    0,  142,  151,
      113,    0,    0,  113,    0,    0,  547,  547,   90,    0,
        0,    0,    0,    0,   29,    0,    0,    0,    0,    0,
      547,   40,    0,  547,  352,  364,  376,  388,  395,  407,

      419,  431,  438,  445,  452,  459,  467,  473
    } ;

static yyconst short int yy_def[309] =
    {   0,
      294,    1,  295,  295,  296,  296,  297,  297,  298,  298,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,   27,  294,  294,
      294,  294,  294,  299,  299,  294,  294,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  294,  294,  294,  300,  294,  294,  301,  294,
      294,  294,  294,  302,  294,  294,  294,  294,  294,  294,
      294,  294,  294,   27,  303,  303,  303,  303,  303,  303,
      303,  303,  294,  294,  294,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,

      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  294,  300,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  301,  294,  302,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  304,  303,  294,  303,   76,
       77,   76,   77,  303,  303,  303,  303,  303,  303,   81,
       81,   82,   82,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,

      299,  294,  305,  306,  304,  307,  205,  294,  308,  294,
      149,  149,  303,  303,  303,  303,  303,  303,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  294,  294,  205,
      294,  308,  252,  294,  303,  303,  303,  303,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  294,  294,  294,  303,
      303,  303,  303,  299,  299,  299,  299,  299,  299,  299,
      294,  299,  299,    0,  294,  294,  294,  294,  294,  294,

      294,  294,  294,  294,  294,  294,  294,  294
    } ;

static yyconst short int yy_nxt[611] =
    {   0,
       12,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   28,   28,
       28,   28,   28,   28,   29,   30,   31,   32,   33,   34,
       34,   34,   35,   36,   12,   37,   34,   38,   39,   40,
       41,   42,   43,   34,   34,   44,   34,   45,   46,   34,
       34,   47,   48,   49,   50,   51,   34,   52,   34,   34,
       53,   54,   55,   57,   57,   60,   60,   65,   65,   71,
       61,   61,   87,  108,   72,   89,   91,   75,   92,   90,
       93,  293,  109,  118,  292,   88,   94,  120,   95,   75,
      119,  121,   58,   58,   66,   66,   73,   75,   74,   74,

       74,   74,   74,   74,   74,   74,   97,  294,   98,  294,
      291,   75,   76,   75,   75,  226,  227,   99,   77,   75,
       78,   75,   75,   76,   79,   75,   75,   80,   75,   75,
       75,   75,   81,   75,   75,   75,   75,   75,   75,   75,
       82,   75,  100,  104,   75,  110,  115,  125,  156,  156,
      126,  137,  127,  138,  290,  185,   75,  101,  111,  116,
      117,  128,  139,  112,   75,  189,  105,  289,  157,  102,
      103,  186,  106,  107,  192,  195,  148,  190,  148,  129,
      140,  146,  146,  146,  146,  146,  146,  146,  146,  193,
      288,  287,  200,  196,  130,  141,  201,  131,  142,  132,

      143,  210,  253,  133,  144,  148,  286,  148,  254,  285,
      149,  149,  149,  149,  149,  149,  149,  149,  202,  202,
      202,  160,  160,  160,  160,  160,  160,  160,  156,  156,
      150,   73,  284,  151,  151,  151,  151,  151,  151,  151,
      151,  161,  283,  206,  202,  202,  202,  152,  157,  207,
      206,  156,  156,  153,  206,  208,  207,  214,  152,  154,
      282,  206,  155,  162,  162,  162,  162,  162,  162,  162,
      162,  157,  253,  281,  280,  279,  162,  162,  254,  278,
      277,  276,  275,  163,  162,  162,  162,  162,  162,  162,
      203,  203,  203,  203,  203,  203,  203,  204,  204,  204,

      204,  204,  204,  204,  209,  209,  209,  209,  209,  209,
      209,  209,  274,  209,  209,  209,  209,  209,  209,  209,
      209,  273,  272,  271,  210,  211,  211,  211,  211,  211,
      211,  211,  211,  210,  270,  294,  269,  268,  267,  266,
      265,  250,  264,  263,  262,  212,  294,  208,  261,  260,
      259,  213,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,

       86,   86,   86,   86,  258,   86,   86,  124,  257,  124,
      124,  124,  124,  124,  124,  124,  256,  124,  124,  134,
      134,  134,  255,  134,  134,  134,  134,  134,  134,  134,
      134,  136,  136,  251,  136,  136,  136,  136,  136,  136,
      247,  136,  136,  147,  147,  147,  147,  246,  147,  147,
      205,  245,  205,  244,  243,  205,  205,  248,  248,  248,
      242,  241,  240,  248,  249,  249,  249,  239,  238,  237,
      249,  209,  209,  236,  235,  234,  233,  209,  252,  232,
      231,  230,  229,  252,  252,  228,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  215,  159,  158,  199,

      198,  197,  194,  191,  188,  187,  184,  183,  182,  181,
      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,
      170,  169,  168,  167,  166,  165,  164,  159,  158,  145,
      135,  123,  122,  114,  113,   96,   85,   84,   83,   70,
       69,   68,   67,  294,   63,   63,   11,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,

      294,  294,  294,  294,  294,  294,  294,  294,  294,  294
    } ;

static yyconst short int yy_chk[611] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    5,    6,    9,   10,   26,
        5,    6,   35,   45,   26,   38,   39,   28,   39,   38,
       40,  292,   45,   50,  285,   35,   40,   51,   40,   28,
       50,   51,    3,    4,    9,   10,   27,   28,   27,   27,

       27,   27,   27,   27,   27,   27,   42,  150,   42,  150,
      279,   27,   27,   27,   27,  171,  171,   42,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   43,   44,   74,   46,   49,   58,   78,   78,
       58,   66,   58,   66,  274,  111,   74,   43,   46,   49,
       49,   58,   66,   46,   74,  114,   44,  271,   78,   43,
       43,  111,   44,   44,  116,  118,  206,  114,  206,   58,
       66,   73,   73,   73,   73,   73,   73,   73,   73,  116,
      270,  269,  122,  118,   58,   66,  122,   58,   66,   58,

       66,  206,  209,   58,   66,   76,  266,   76,  209,  264,
       76,   76,   76,   76,   76,   76,   76,   76,  125,  125,
      125,   81,   81,   81,   81,   81,   81,   81,  156,  156,
       76,   77,  259,   77,   77,   77,   77,   77,   77,   77,
       77,   81,  258,  146,  202,  202,  202,   77,  156,  146,
      207,  157,  157,   77,  146,  146,  207,  156,   77,   77,
      257,  207,   77,   82,   82,   82,   82,   82,   82,   82,
       82,  157,  252,  256,  255,  254,   82,   82,  252,  251,
      249,  247,  246,   82,   82,   82,   82,   82,   82,   82,
      133,  133,  133,  133,  133,  133,  133,  144,  144,  144,

      144,  144,  144,  144,  148,  148,  148,  148,  148,  148,
      148,  148,  245,  210,  210,  210,  210,  210,  210,  210,
      210,  242,  241,  240,  148,  149,  149,  149,  149,  149,
      149,  149,  149,  210,  239,  205,  237,  235,  232,  231,
      228,  205,  227,  226,  224,  149,  205,  205,  222,  221,
      220,  149,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,

      299,  299,  299,  299,  218,  299,  299,  300,  217,  300,
      300,  300,  300,  300,  300,  300,  214,  300,  300,  301,
      301,  301,  213,  301,  301,  301,  301,  301,  301,  301,
      301,  302,  302,  208,  302,  302,  302,  302,  302,  302,
      201,  302,  302,  303,  303,  303,  303,  200,  303,  303,
      304,  198,  304,  197,  196,  304,  304,  305,  305,  305,
      195,  194,  193,  305,  306,  306,  306,  192,  191,  190,
      306,  307,  307,  186,  184,  183,  181,  307,  308,  178,
      176,  175,  174,  308,  308,  172,  170,  169,  168,  167,
      166,  165,  164,  162,  160,  159,  158,  155,  154,  121,

      120,  119,  117,  115,  113,  112,  110,  109,  108,  106,
      104,  103,  101,  100,   99,   98,   97,   96,   95,   94,
       93,   92,   91,   90,   89,   88,   87,   80,   79,   70,
       60,   54,   52,   48,   47,   41,   33,   32,   31,   25,
       24,   17,   15,   11,    8,    7,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,

      294,  294,  294,  294,  294,  294,  294,  294,  294,  294
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "input.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#define CONST_STRING 1

#define MULTILINE_COMMENT 2

#define ONELINE_COMMENT 3

#define CHAR 4

#line 12 "input.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
char buffer[1000];
#line 616 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 18 "input.l"




int remove_char(char *s, int pos);
void remove_underline();
void remove_f64();
void remove_i32();
int int_buffer;
char buf_char[2];



#line 781 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 295 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 547 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 31 "input.l"
{ printf("(%s) - Found KW_AS\n", yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 32 "input.l"
{ printf("(%s) - Found KW_BREAK\n", yytext); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 33 "input.l"
{ printf("(%s) - Found KW_CONST\n", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 34 "input.l"
{ printf("(%s) - Found KW_CONTINUE\n", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 35 "input.l"
{ printf("(%s) - Found KW_CRATE\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 36 "input.l"
{ printf("(%s) - Found KW_ELSE\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 37 "input.l"
{ printf("(%s) - Found KW_ENUM\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 38 "input.l"
{ printf("(%s) - Found KW_EXTERN\n", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 39 "input.l"
{ printf("(%s) - Found KW_FN\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 40 "input.l"
{ printf("(%s) - Found KW_FOR\n", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 41 "input.l"
{ printf("(%s) - Found KW_FLOAT64\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 42 "input.l"
{ printf("(%s) - Found KW_IF\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 43 "input.l"
{ printf("(%s) - Found KW_IMPL\n", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 44 "input.l"
{ printf("(%s) - Found KW_IN\n", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 45 "input.l"
{ printf("(%s) - Found KW_LET\n", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 46 "input.l"
{ printf("(%s) - Found KW_LOOP\n", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 47 "input.l"
{ printf("(%s) - Found KW_MATCH\n", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 48 "input.l"
{ printf("(%s) - Found KW_MOD\n", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 49 "input.l"
{ printf("(%s) - Found KW_MOVE\n", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 50 "input.l"
{ printf("(%s) - Found KW_MUT\n", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 51 "input.l"
{ printf("(%s) - Found KW_PUB\n", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 52 "input.l"
{ printf("(%s) - Found KW_REF\n", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 53 "input.l"
{ printf("(%s) - Found KW_RETURN\n", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 54 "input.l"
{ printf("(%s) - Found KW_SELFVALUE\n", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 55 "input.l"
{ printf("(%s) - Found KW_SELFTYPE\n", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 56 "input.l"
{ printf("(%s) - Found KW_STATIC\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 57 "input.l"
{ printf("(%s) - Found KW_STRUCT\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 58 "input.l"
{ printf("(%s) - Found KW_SUPER\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 59 "input.l"
{ printf("(%s) - Found KW_TRAIT\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 60 "input.l"
{ printf("(%s) - Found KW_TYPE\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 61 "input.l"
{ printf("(%s) - Found KW_UNSAFE\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 62 "input.l"
{ printf("(%s) - Found KW_USE\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 63 "input.l"
{ printf("(%s) - Found KW_WHERE\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 64 "input.l"
{ printf("(%s) - Found KW_WHILE\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 65 "input.l"
{ printf("(%s) - Found KW_ASYNC\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 66 "input.l"
{ printf("(%s) - Found KW_AWAITE\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 67 "input.l"
{ printf("(%s) - Found KW_DYN\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 68 "input.l"
{ printf("(%s) - Found KW_INTEGER32\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 69 "input.l"
{ printf("(%s) - Found KW_STRING\n", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 70 "input.l"
{ printf("(%s) - Found KW_CHAR\n", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 71 "input.l"
{ printf("(%s) - Found KW_BOOLEAN\n", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 73 "input.l"
{ printf("(%s) - Found BOOLEAN_FALSE\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 74 "input.l"
{ printf("(%s) - Found BOOLEAN_TRUE\n", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 76 "input.l"
{buffer[0]=0; BEGIN(CONST_STRING);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 77 "input.l"
{strcat(buffer,yytext);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 78 "input.l"
{strcat(buffer, "");}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 79 "input.l"
{strcat(buffer, "\\");}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 80 "input.l"
{strcat(buffer, "\n");}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 81 "input.l"
{strcat(buffer, "\t");}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 82 "input.l"
{strcat(buffer, "\0");}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 83 "input.l"
{strcat(buffer, "\r");}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 84 "input.l"
{strcat(buffer, "\"");}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 85 "input.l"
{strcat(buffer, "\'");}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 86 "input.l"
{ buf_char[0] = strtol(yytext+2, NULL, 16); buf_char[1] = 0; strcat(buffer, buf_char);}
	YY_BREAK
case YY_STATE_EOF(CONST_STRING):
#line 87 "input.l"
{printf("(%s) - Found ERROR_STRING\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 88 "input.l"
{printf("(%s) - Found NOT_ESCAPED_SLASH\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 89 "input.l"
{printf("(%s) - Found CONST_STRING\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 91 "input.l"
{buffer[0]=0; BEGIN(CHAR);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 92 "input.l"
{ yytext[strlen(yytext)-1] = '\0'; buf_char[0] = strtol(yytext+2, NULL, 16); printf( "(%c) - Found CHAR\n", buf_char[0] ); BEGIN(INITIAL);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 93 "input.l"
{strcat(buffer,yytext);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 94 "input.l"
{strcat(buffer, "\\");}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 95 "input.l"
{strcat(buffer, "\n");}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 96 "input.l"
{strcat(buffer, "\t");}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 97 "input.l"
{strcat(buffer, "\0");}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 98 "input.l"
{strcat(buffer, "\r");}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 99 "input.l"
{strcat(buffer, "\"");}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 100 "input.l"
{strcat(buffer, "\'");}
	YY_BREAK
case YY_STATE_EOF(CHAR):
#line 101 "input.l"
{printf("(%s) - Error CHAR\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 102 "input.l"
{
if(strlen(buffer)==1){
printf("(%s) - Found CHAR\n", buffer); BEGIN(INITIAL);
}else{
printf("(%s) - Error CHAR\n", buffer); BEGIN(INITIAL);
}
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 110 "input.l"
{buffer[0]=0; BEGIN(MULTILINE_COMMENT);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 111 "input.l"
{strcat(buffer,yytext);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 112 "input.l"
{strcat(buffer, "*");}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 113 "input.l"
{strcat(buffer, "/");}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 114 "input.l"
{ printf("(%s) - Error COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 115 "input.l"
{printf("(%s) - Found MULTILINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 117 "input.l"
{buffer[0]=0; BEGIN(ONELINE_COMMENT);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 118 "input.l"
{strcat(buffer, yytext);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 119 "input.l"
{printf("(%s) - Found ONELINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(ONELINE_COMMENT):
#line 120 "input.l"
{printf("(%s) - Found ONELINE_COMMENT\n", buffer); BEGIN(INITIAL);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 123 "input.l"
{ printf("(%s) - Found PLUS_OPERATOR\n", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 124 "input.l"
{ printf("(%s) - Found MINUS_OPERATOR\n", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 125 "input.l"
{ printf("(%s) - Found MUL_OPERATOR\n", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 126 "input.l"
{ printf("(%s) - Found DIV_OPERATOR\n", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 127 "input.l"
{ printf("(%s) - Found LESS_OR_EQUAL_OPERATOR\n", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 128 "input.l"
{ printf("(%s) - Found MORE_OR_EQUAL_OPERATOR\n", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 129 "input.l"
{ printf("(%s) - Found LESS_OPERATOR\n", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 130 "input.l"
{ printf("(%s) - Found MORE_OPERATOR\n", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 131 "input.l"
{ printf("(%s) - Found NOT_EQUAL_OPERATOR\n", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 132 "input.l"
{ printf("(%s) - Found ASSIGNMENT_OPERATOR\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 134 "input.l"
{ printf("(%s) - Found EQUAL_OPERATOR\n", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 135 "input.l"
{ printf("(%s) - Found NOT_OPERATOR\n", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 136 "input.l"
{ printf("(%s) - Found OR_OPERATOR\n", yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 137 "input.l"
{ printf("(%s) - Found AND_OPERATOR\n", yytext); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 139 "input.l"
{ printf("(%s) - Found RANGE_OPERATOR\n", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 140 "input.l"
{ printf("(%s) - Found RANGE_EQUAL_OPERATOR\n", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 141 "input.l"
{ printf("(%s) - Found ARROW_OPERATOR\n", yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 143 "input.l"
{ printf("(%s) - Found SQUARE_BRACKET\n", yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 144 "input.l"
{ printf("(%s) - Found SQUARE_BRACKET\n", yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 145 "input.l"
{ printf("(%s) - Found ROUND_BRACKET\n", yytext); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 146 "input.l"
{ printf("(%s) - Found ROUND_BRACKET\n", yytext); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 147 "input.l"
{ printf("(%s) - Found BRACE\n", yytext); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 148 "input.l"
{ printf("(%s) - Found BRACE\n", yytext); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 149 "input.l"
{ printf("(%s) - Found SEMICOLON\n", yytext); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 150 "input.l"
{ printf("(%s) - Found COMMA\n", yytext); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 151 "input.l"
{ printf("(%s) - Found COLON\n", yytext); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 152 "input.l"
{ printf("(%s) - Found DOT\n", yytext); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 153 "input.l"
{ printf("(%s) - Found AMPERSAND\n", yytext); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 155 "input.l"
{ printf("(%s) - Found IDENTIFIER\n", yytext); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 157 "input.l"
{
remove_underline();
remove_i32();
printf("(%d) - Found DECIMAL_INTEGER\n", atoi(buffer));
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 163 "input.l"
{
remove_f64();
remove_underline();
printf("(%f) - Found FLOAT_CONST\n", atof(buffer));
}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 169 "input.l"
{
remove_f64();
remove_underline();
printf("(%f) - Found FLOAT_CONST\n", atof(buffer));
}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 175 "input.l"
{
remove_underline();
remove_i32();
printf("(%d) - Found OCTAL_INTEGER\n", strtol(buffer+2, NULL, 8));
}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 181 "input.l"
{
remove_underline();
remove_i32();
printf("(%d) - Found HEXADECIMAL_INTEGER\n", strtol(buffer+2, NULL, 16));
}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 187 "input.l"
{
remove_underline();
remove_i32();
printf("(%d) - Found BINARY_INTEGER\n", strtol(buffer+2, NULL, 2));
}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 193 "input.l"
{ printf("(%s) - Error IDENTIFIER\n", yytext); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 195 "input.l"
{}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 196 "input.l"
{}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 198 "input.l"
ECHO;
	YY_BREAK
#line 1480 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 295 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 295 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 294);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 198 "input.l"


int remove_char(char *s, int pos)
{
  int length = strlen(s);

  if (pos >= length) return 0;

  for (int i = pos; i < length; i++)
    s[i] = s[i + 1];

  return 1;
}

void remove_underline()
{
    strcpy(buffer, yytext);
    char* ptr = strchr(buffer, '_');
    while (ptr != NULL){
        ptr = strchr(buffer, '_');
        int pos = ptr - buffer;
        remove_char(buffer, pos);
    }
}

void remove_f64()
{
    strcpy(buffer, yytext);
    char* ptr = strstr(buffer, "f64");
    if (ptr != NULL){
        int pos = ptr - buffer;
        buffer[pos] = '\0';
    }
}

void remove_i32()
{
    strcpy(buffer, yytext);
    char* ptr = strstr(buffer, "i32");
        if (ptr != NULL){
            int pos = ptr - buffer;
            buffer[pos] = '\0';
        }
}